version: 2.1
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          PGHOST: localhost
          PGUSER: circleci
          RAILS_ENV: test
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_DB: school_test
          POSTGRES_USER: circleci

    steps:
      - checkout

      - run:
          name: Install bundler
          command: gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - ruby/load-cache
      - ruby/install-deps
      - ruby/save-cache

      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec rake db:schema:load

      - run: bundle exec rspec

  deploy:
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - heroku/deploy-via-git

orbs:
  heroku: circleci/heroku@1.0.1
  ruby: circleci/ruby@0.2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
