version: 2.1
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/ruby:2.5.8-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          RAILS_ENV: test

    steps:
      - checkout

      - run:
          name: Install bundler
          command: gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
          - gems-v1-{{ checksum "Gemfile.lock"  }}
          - gems-v1-
      - ruby/install-deps
      - ruby/save-cache

      - node/with-cache:
          steps:
            - run: yarn install

      - run: bundle exec rubocop

      - run: bin/rails db:schema:load

      - run: bin/rspec

  deploy:
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - heroku/deploy-via-git

orbs:
  heroku: circleci/heroku@1.0.1
  node: circleci/node@1.1.6
  ruby: circleci/ruby@0.2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
