# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fcb65401ae3065d35f27b950e42e114e4159531db637ad3934c8e1aaffeebae82f0497bd8d8149a49025e693c6e7fd84c63651d3c348e06f5240feda452ec13

test:
  secret_key_base: 7990c6c9eeccd89c56589b9299ac5c9e212d76f45c6649837f09357a40d029e64988671ae59e5973415af1f027781c59616eec1790df41ca063344418f88448d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
